#!/bin/bash
# Fix Auto-restart for Clawdbot Remote Node
# Configures LaunchAgent on remote Mac for automatic startup

set -e

# shellcheck source=lib/common.sh
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

echo "🔧 Clawdbot Auto-restart Fix"
echo "============================"
echo ""

# Load configuration
load_env

# Configuration from environment (no hardcoded values)
: "${REMOTE_HOST:?Set REMOTE_HOST in .env or environment}"
: "${REMOTE_USER:?Set REMOTE_USER in .env or environment}"
: "${GATEWAY_HOST:?Set GATEWAY_HOST in .env or environment}"
: "${GATEWAY_IP:?Set GATEWAY_IP in .env or environment}"
: "${GATEWAY_PORT:=18789}"

# Polling configuration
MAX_WAIT_SECONDS=60
POLL_INTERVAL=3

# Check prerequisites
check_prereqs() {
    print_step "Checking prerequisites..."

    # Test SSH connection
    if ! ssh_check "${REMOTE_USER}@${REMOTE_HOST}"; then
        print_error "Cannot SSH to ${REMOTE_USER}@${REMOTE_HOST}"
        echo "    Please ensure:"
        echo "    1. Remote Mac is powered on"
        echo "    2. SSH key is configured"
        echo "    3. Network is reachable"
        exit 1
    fi

    print_success "SSH connection verified"

    # Check if clawdbot is installed on remote
    if ! ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" 'export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && command -v clawdbot' &>/dev/null; then
        print_error "Clawdbot not found on remote Mac"
        echo "    Please install: npm install -g clawdbot@latest"
        exit 1
    fi

    print_success "Clawdbot installed on remote"
    echo ""
}

# Generate startup script from template
generate_startup_script() {
    local template="$SCRIPT_DIR/templates/start-node.sh.template"

    if [ -f "$template" ]; then
        # Use template file with variable substitution
        sed -e "s|{{GATEWAY_IP}}|${GATEWAY_IP}|g" \
            -e "s|{{GATEWAY_PORT}}|${GATEWAY_PORT}|g" \
            -e "s|{{GATEWAY_HOST}}|${GATEWAY_HOST}|g" \
            "$template"
    else
        # Fallback: generate inline if template not found
        cat << EOF
#!/bin/bash
# Clawdbot Node Startup Script
# Auto-generated by fix-auto-restart.sh

LOG_FILE="\$HOME/.clawdbot/logs/startup.log"
mkdir -p "\$(dirname "\$LOG_FILE")"
exec >> "\$LOG_FILE" 2>&1

echo "=========================================="
echo "Clawdbot Node Startup - \$(date)"
echo "=========================================="

export NVM_DIR="\$HOME/.nvm"
[ -s "\$NVM_DIR/nvm.sh" ] && . "\$NVM_DIR/nvm.sh"

if ! command -v clawdbot &> /dev/null; then
    echo "ERROR: clawdbot not found"
    exit 1
fi

sleep 10
clawdbot node start --host ${GATEWAY_HOST} --port ${GATEWAY_PORT}
EOF
    fi
}

# Generate LaunchAgent plist from template
generate_plist() {
    local remote_home="$1"
    local template="$SCRIPT_DIR/templates/com.clawdbot.node.plist.template"

    if [ -f "$template" ]; then
        # Use template file with variable substitution
        sed -e "s|{{REMOTE_HOME}}|${remote_home}|g" "$template"
    else
        # Fallback: generate inline if template not found
        cat << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.clawdbot.node</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>-c</string>
        <string>\$HOME/.clawdbot/scripts/start-node.sh</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>ThrottleInterval</key>
    <integer>30</integer>
    <key>StandardOutPath</key>
    <string>${remote_home}/.clawdbot/logs/launchd-stdout.log</string>
    <key>StandardErrorPath</key>
    <string>${remote_home}/.clawdbot/logs/launchd-stderr.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>HOME</key>
        <string>${remote_home}</string>
    </dict>
    <key>WorkingDirectory</key>
    <string>${remote_home}</string>
</dict>
</plist>
EOF
    fi
}

# Create startup script and LaunchAgent on remote
setup_remote() {
    print_step "Setting up auto-restart on remote Mac..."

    # Get remote user's home directory
    local remote_home
    remote_home=$(ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" 'echo $HOME')

    # Create directories on remote
    ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" 'mkdir -p ~/.clawdbot/scripts ~/.clawdbot/logs'

    # Generate and upload startup script
    print_step "Creating startup script..."
    generate_startup_script | ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" 'cat > ~/.clawdbot/scripts/start-node.sh && chmod +x ~/.clawdbot/scripts/start-node.sh'
    print_success "Startup script created"

    # Generate and upload LaunchAgent plist
    print_step "Creating LaunchAgent..."
    generate_plist "$remote_home" | ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" 'cat > ~/Library/LaunchAgents/com.clawdbot.node.plist'

    # Validate and load LaunchAgent
    ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" << 'ENDSSH'
# Verify plist syntax
if ! plutil -lint ~/Library/LaunchAgents/com.clawdbot.node.plist > /dev/null 2>&1; then
    echo "ERROR: Invalid plist syntax"
    exit 1
fi
echo "✓ LaunchAgent plist validated"

# Unload existing agent if present
launchctl unload ~/Library/LaunchAgents/com.clawdbot.node.plist 2>/dev/null || true
sleep 1

# Load the agent
launchctl load ~/Library/LaunchAgents/com.clawdbot.node.plist

# Verify it's loaded
if launchctl list | grep -q "com.clawdbot.node"; then
    echo "✓ LaunchAgent loaded successfully"
else
    echo "ERROR: LaunchAgent failed to load"
    exit 1
fi
ENDSSH

    print_success "Remote setup complete"
}

# Verify setup with polling instead of fixed sleep
verify_setup() {
    print_step "Verifying setup..."
    echo ""

    # Check LaunchAgent status
    echo "LaunchAgent status:"
    ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" 'launchctl list | grep clawdbot || echo "  (not found)"'
    echo ""

    # Poll for node to become ready instead of fixed sleep
    echo "⏳ Waiting for node to start..."
    local waited=0
    local node_ready=false

    while [ $waited -lt $MAX_WAIT_SECONDS ]; do
        local status
        status=$(ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" 'export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && clawdbot node status 2>&1 | head -1' 2>/dev/null || echo "starting")

        if echo "$status" | grep -qi "connected\|running\|online"; then
            print_success "Node is running"
            node_ready=true
            break
        fi

        sleep "$POLL_INTERVAL"
        waited=$((waited + POLL_INTERVAL))
        echo "   Waiting... ($waited/${MAX_WAIT_SECONDS}s) - $status"
    done

    if [ "$node_ready" = false ]; then
        print_warning "Node may still be starting (timeout reached)"
    fi

    echo ""
    echo "Node status:"
    ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" 'export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && clawdbot node status 2>/dev/null || echo "  Node not responding"'

    echo ""
    echo "Recent startup log:"
    ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" 'tail -10 ~/.clawdbot/logs/startup.log 2>/dev/null || echo "  (no log yet)"'
    echo ""
}

# Display summary
show_summary() {
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    print_success "Auto-restart Configuration Complete!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "📁 Files created on remote Mac:"
    echo "   ~/.clawdbot/scripts/start-node.sh"
    echo "   ~/Library/LaunchAgents/com.clawdbot.node.plist"
    echo "   ~/.clawdbot/logs/ (log directory)"
    echo ""
    echo "🔧 Management commands (run on remote Mac):"
    echo "   Start:   launchctl load ~/Library/LaunchAgents/com.clawdbot.node.plist"
    echo "   Stop:    launchctl unload ~/Library/LaunchAgents/com.clawdbot.node.plist"
    echo "   Status:  launchctl list | grep clawdbot"
    echo "   Logs:    tail -f ~/.clawdbot/logs/startup.log"
    echo ""
    echo "🧪 Test with reboot:"
    echo "   ssh ${REMOTE_USER}@${REMOTE_HOST} 'sudo reboot'"
    echo "   # Wait 2-3 minutes, then check:"
    echo "   ssh ${REMOTE_USER}@${REMOTE_HOST} 'clawdbot node status'"
    echo ""
    echo "📚 Documentation:"
    echo "   See: docs/AUTO_RESTART_FIX.md"
    echo ""
}

# Show help
show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Configures auto-restart for Clawdbot node on remote Mac."
    echo ""
    echo "Options:"
    echo "  --verify-only   Only check current status, don't make changes"
    echo "  --help, -h      Show this help message"
    echo ""
    echo "Required environment variables (set in .env):"
    echo "  REMOTE_HOST     IP address of remote Mac"
    echo "  REMOTE_USER     Username on remote Mac"
    echo "  GATEWAY_HOST    Hostname of gateway (e.g., Mac.local)"
    echo "  GATEWAY_IP      IP address of gateway"
    echo ""
    echo "Optional:"
    echo "  GATEWAY_PORT    Gateway port (default: 18789)"
    echo ""
    exit 0
}

# Main execution
main() {
    echo "This script will configure auto-restart for the Clawdbot node"
    echo "on remote Mac: ${REMOTE_USER}@${REMOTE_HOST}"
    echo ""

    check_prereqs
    setup_remote
    verify_setup
    show_summary
}

# Handle arguments
case "${1:-}" in
    --help|-h)
        show_help
        ;;
    --verify-only)
        check_prereqs
        verify_setup
        exit 0
        ;;
    *)
        main
        ;;
esac
